# This file was generated by GoReleaser. DO NOT EDIT.
cask "tbunny" do
  name "tbunny"
  desc "A fast, keyboard-driven terminal UI for managing RabbitMQ clusters"
  homepage "https://github.com/anadale/tbunny"
  version "0.23.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tbunny"

  on_macos do
    on_intel do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Darwin_x86_64.tar.gz"
      sha256 "657b96756a75cd04996bbb6083359b8488630b9d3eea1104a4c6469ec5946f00"
    end
    on_arm do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Darwin_arm64.tar.gz"
      sha256 "d2b25e35f51dff54425c3884b2d7b345bbc8dad94df8fb9c45c3c3b670f06c45"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Linux_x86_64.tar.gz"
      sha256 "55a51b1ed668604dc674f3a5ef8382e17d1a246f26d0f4dc801d53045ffad8e1"
    end
    on_arm do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Linux_arm64.tar.gz"
      sha256 "44cb3f6944bad47b2c2dde6efcf86ca087b33dffdd856f3affcebd725b246ba6"
    end
  end

  # No zap stanza required
end
