# This file was generated by GoReleaser. DO NOT EDIT.
cask "tbunny" do
  name "tbunny"
  desc "A fast, keyboard-driven terminal UI for managing RabbitMQ clusters"
  homepage "https://github.com/anadale/tbunny"
  version "0.18.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tbunny"

  on_macos do
    on_intel do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f9cd25ead34160e1feb42b400b8796d39308265e897ae5a732482d71dcf40398"
    end
    on_arm do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Darwin_arm64.tar.gz"
      sha256 "467b6ed745f293c0423946dca6b31273991aeff93fb6ab9d56ff859275d1e43a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Linux_x86_64.tar.gz"
      sha256 "4b09451d86275042c890ba0e844c357e327d4d8a4c55707f4f0ca139dc428193"
    end
    on_arm do
      url "https://github.com/anadale/tbunny/releases/download/v#{version}/tbunny_#{version}_Linux_arm64.tar.gz"
      sha256 "5008c7bae864f0864a21611b2d712df33016c7ebc11c32986525a68b7583b818"
    end
  end

  # No zap stanza required
end
